# Generated by Django 4.0.6 on 2022-07-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('fash', 'Fashion'), ('tech', 'Technology'), ('others', 'Others')], default='others', max_length=100),
        ),
    ]
