# Generated by Django 4.0.6 on 2022-07-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_posts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ImageField(default='null', upload_to='blog_post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('fash', 'Fashion'), ('others', 'Others'), ('tech', 'Technology')], default='others', max_length=100),
        ),
    ]
