# Generated by Django 4.0.6 on 2022-07-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('others', 'Others'), ('tech', 'Technology'), ('fash', 'Fashion')], default='others', max_length=100),
        ),
    ]
