# Generated by Django 4.0.6 on 2022-07-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_posts_images_alter_posts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('fash', 'Fashion'), ('others', 'Others')], default='others', max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='images',
            field=models.ImageField(upload_to='blog_post'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
