# Generated by Django 4.0.6 on 2022-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_posts_category_alter_posts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='images',
            field=models.ImageField(blank=True, upload_to='blog_post'),
        ),
    ]
