# Generated by Django 4.0.6 on 2022-07-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('others', 'Others'), ('tech', 'Technology'), ('fash', 'Fashion')], default='others', max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='images',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='blog_post'),
        ),
    ]
