# Generated by Django 4.0.6 on 2022-07-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('fash', 'Fashion'), ('others', 'Others'), ('tech', 'Technology')], default='others', max_length=100),
        ),
    ]
