# Generated by Django 4.0.6 on 2022-07-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_category_remove_posts_category_posts_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.IntegerField(choices=[(1, 'Publish'), (0, 'Draft')], default=0),
        ),
    ]
