# Generated by Django 4.0.6 on 2022-07-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_posts_status'),
        ('post', '0016_category_remove_posts_category_posts_category'),
    ]

    operations = [
    ]
