# Generated by Django 4.0.6 on 2022-07-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_merge_20220710_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='posts',
            name='reply',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
