# Generated by Django 4.0.6 on 2022-07-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_posts_options_posts_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='reply',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
