# Generated by Django 4.0.6 on 2022-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_alter_posts_reply_alter_posts_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='reply',
        ),
    ]
