# Generated by Django 4.0.6 on 2022-07-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_userreply_remove_posts_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReply',
        ),
    ]
