# Generated by Django 4.0.6 on 2022-07-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_alter_posts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_txt',
            field=models.CharField(max_length=200),
        ),
    ]
