# Generated by Django 4.0.6 on 2022-07-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_alter_comment_comment_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_txt',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
