# Generated by Django 4.0.6 on 2022-07-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_posts_options_alter_posts_status'),
        ('post', '0025_rename_comment_txt_comment_comments_and_more'),
    ]

    operations = [
    ]
