# Generated by Django 4.0.6 on 2022-07-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_alter_posts_status'),
        ('post', '0027_alter_category_name'),
    ]

    operations = [
    ]
