<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-07-15 20:06
=======
# Generated by Django 4.0.6 on 2022-07-19 20:30
>>>>>>> 138e73d7eb9aaf990239723f13391a1e6ceff83f

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0038_alter_posts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
